org: kawaym
app: webscraper-ecommerce
service: webscraper-ecommerce
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  esbuild:
    packager: 'pnpm'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  healthCheck:
    handler: src/functions/health.health
    events:
      - httpApi:
          method: get
          path: /health

plugins:
  - serverless-esbuild
  - serverless-offline
